# Instructions

* This notebook has a combination of fill-in-the-blank and entire code blocks you need to solve. 

# Hypothesis Testing


We would like to know if the effects we see in the sample(observed data) are likely to occur in the population. 

The way classical hypothesis testing works is by conducting a statistical test to answer the following question:
> Given the sample and an effect, what is the probability of seeing that effect just by chance?

Here are the steps on how we would do this

1. Compute test statistic
2. Define null hypothesis
3. Compute p-value
4. Interpret the result

If p-value is very low (below 0.05), the effect is considered statistically significant. That means that effect is unlikely to have occured by chance. The inference? The effect is likely to be seen in the population too. 

This process is very similar to the *proof by contradiction* paradigm. We first assume that the effect is false. That's the null hypothesis. Next step is to compute the probability of obtaining that effect (the p-value). If p-value is very low (<0.05 as a rule of thumb), we reject the null hypothesis. 

In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib as mpl
%matplotlib inline

In [2]:
import seaborn as sns
sns.set(color_codes=True)

In [3]:
weed_pd = pd.read_csv("../data/Weed_Price.csv", parse_dates=[-1])
weed_pd.head()

State   HighQ  HighQN    MedQ  MedQN    LowQ  LowQN       date
0     Alabama  339.06    1042  198.64    933  149.49    123 2014-01-01
1      Alaska  288.75     252  260.60    297  388.58     26 2014-01-01
2     Arizona  303.31    1941  209.35   1625  189.45    222 2014-01-01
3    Arkansas  361.85     576  185.62    544  125.87    112 2014-01-01
4  California  248.78   12096  193.56  12812  192.92    778 2014-01-01

* Parse the `date` column to create two new columns: one for `month` and one for `year`.

In [5]:
weed_pd["month"] = weed_pd['date'].dt.month
weed_pd["year"] = weed_pd['date'].dt.year

In [6]:
weed_pd.head()

State   HighQ  HighQN    MedQ  MedQN    LowQ  LowQN       date  month  \
0     Alabama  339.06    1042  198.64    933  149.49    123 2014-01-01      1   
1      Alaska  288.75     252  260.60    297  388.58     26 2014-01-01      1   
2     Arizona  303.31    1941  209.35   1625  189.45    222 2014-01-01      1   
3    Arkansas  361.85     576  185.62    544  125.87    112 2014-01-01      1   
4  California  248.78   12096  193.56  12812  192.92    778 2014-01-01      1   

   year  
0  2014  
1  2014  
2  2014  
3  2014  
4  2014

### Let's work on weed prices in California in 2014


* Parse the `weed_pd` DataFrame so that it contains only entries for California from 2014.

In [8]:
weed_ca_2014 = weed_pd[(weed_pd['State'] == 'California') & (weed_pd['year'] == 2014)]

In [9]:
print(weed_ca_2014['State'].unique())
print(weed_ca_2014['year'].unique())

['California']
[2014]


* Find the mean and standard deviation of high quality weed's price.

In [10]:
weed_ca_hq_mean = weed_ca_2014['HighQ'].mean()
weed_ca_hq_mean

245.8942307692309

In [11]:
weed_ca_hq_std = weed_ca_2014['HighQ'].std()
weed_ca_hq_std

1.289907939371412

In [12]:
print("Mean:", weed_ca_hq_mean )
print("Standard Deviation:", weed_ca_hq_std )

Mean: 245.8942307692309
Standard Deviation: 1.289907939371412


In [15]:
print("Mean:", _________ )
print("Standard Deviation:", _________ )

Mean: 245.8942307692309
Standard Deviation: 1.289907939371412


* Calculate the 95% confidence interval on the mean.

In [14]:
stats.norm.interval?

In [17]:
stats.norm.interval(0.95 , loc= weed_ca_hq_mean , scale = weed_ca_2014.HighQ.std()/np.sqrt(len(weed_ca_2014)))

(245.761718492726, 246.02674304573577)

In [13]:
stats.norm.interval?

In [8]:
stats.norm.interval(___ , loc= ________ , scale = weed_ca_2014.HighQ.std()/np.sqrt(len(weed_ca_2014)))

(245.761718492726, 246.02674304573577)

### Question: Are high-quality weed prices in Jan 2014 significantly higher than in Jan 2015?

* Make two `numpy` arrays by subetting the original DataFrame: each array should list the `HighQ` entries for California in January of 2014 and 2015.

In [27]:
#Get the data
weed_ca_jan2014 = weed_pd[(weed_pd['State'] == 'California') & (weed_pd['month'] == 1) & (weed_pd['year'] == 2014)]['HighQ'].values

weed_ca_jan2015 = weed_pd[(weed_pd['State'] == 'California') & (weed_pd['month'] == 1) & (weed_pd['year'] == 2015)]['HighQ'].values


In [28]:
print(type(weed_ca_jan2014))
weed_ca_jan2014

<class 'numpy.ndarray'>


array([248.78, 248.67, 248.67, 248.65, 248.68, 248.68, 248.64, 248.63,
       248.58, 248.56, 248.54, 248.47, 248.45, 248.41, 248.48, 248.44,
       248.43, 248.49, 248.44, 248.39, 248.33, 248.28, 248.25, 248.22,
       248.18, 248.21, 248.24, 248.28, 248.23, 248.28, 248.23])

In [69]:
weed_ca_jan2015

array([243.96, 243.95, 243.93, 243.91, 243.91, 243.83, 243.79, 243.79,
       243.72, 243.75, 243.73, 243.68, 243.66, 243.6 , 243.58, 243.58,
       243.53, 243.49, 243.5 , 243.48, 243.51, 243.45, 243.43, 243.47,
       243.46, 243.42, 243.4 , 243.34, 243.27, 243.28, 243.27])

In [20]:
#Get the data
weed_ca_jan2014 = 
weed_ca_jan2015 = 

In [24]:
print(type(weed_ca_jan2014))
weed_ca_jan2014

<class 'numpy.ndarray'>


array([248.78, 248.67, 248.67, 248.65, 248.68, 248.68, 248.64, 248.63,
       248.58, 248.56, 248.54, 248.47, 248.45, 248.41, 248.48, 248.44,
       248.43, 248.49, 248.44, 248.39, 248.33, 248.28, 248.25, 248.22,
       248.18, 248.21, 248.24, 248.28, 248.23, 248.28, 248.23])

* Find the mean value for each of the arrays.

In [29]:
print("Mean-2014 Jan:", weed_ca_jan2014.mean() )
print("Mean-2015 Jan:", weed_ca_jan2015.mean() )

Mean-2014 Jan: 248.4454838709677
Mean-2015 Jan: 243.60225806451612


In [10]:
print("Mean-2014 Jan:", ______ )
print("Mean-2015 Jan:", ______ )

Mean-2014 Jan: 248.445483871
Mean-2015 Jan: 243.602258065


* Calculate the effect size of one year on the mean value of weed prices in California. What difference does one year make in terms of average weed prices?

In [35]:
weed_ca_hq_mean_difference = np.abs([weed_ca_jan2014.mean() - weed_ca_jan2015.mean()])
weed_ca_hq_mean_difference

array([4.84322581])

In [42]:
print("Effect size:", weed_ca_hq_mean_difference[0] )

Effect size: 4.843225806451585


In [11]:
print("Effect size:", ______________ )

Effect size: 4.84322580645


**Null Hypothesis**: Mean prices aren't significantly different

Perform **t-test** and determine the p-value. 

In [45]:
stats.ttest_ind?

In [50]:
stats.ttest_ind(weed_ca_jan2014 , weed_ca_jan2015, equal_var=True)

Ttest_indResult(statistic=98.01132523815805, pvalue=6.297971818508403e-68)

In [26]:
stats.ttest_ind?

In [12]:
stats.ttest_ind(________ , ________ , equal_var=True)

Ttest_indResult(statistic=98.011325238158051, pvalue=6.2979718185084028e-68)

p-value is the probability that the effective size was by chance. And here, p-value is almost 0.

*Conclusion*: The price difference is significant. But is a price increase of $4.85 a big deal? The price decreased in 2015 by almost 2%. Always remember to look at effect size. 

### t-test Challenge
**Problem** Determine if prices of medium quality weed for Jan 2015 and Feb 2015 are significantly different for New York. 
* _**CoderGirl**: Use what you've learned above to answer the below two questions._

In [51]:
# Your code here

weed_pd.head()

State   HighQ  HighQN    MedQ  MedQN    LowQ  LowQN       date  month  \
0     Alabama  339.06    1042  198.64    933  149.49    123 2014-01-01      1   
1      Alaska  288.75     252  260.60    297  388.58     26 2014-01-01      1   
2     Arizona  303.31    1941  209.35   1625  189.45    222 2014-01-01      1   
3    Arkansas  361.85     576  185.62    544  125.87    112 2014-01-01      1   
4  California  248.78   12096  193.56  12812  192.92    778 2014-01-01      1   

   year  
0  2014  
1  2014  
2  2014  
3  2014  
4  2014

In [63]:
weed_pd_mq_ny_jan2015 = weed_pd[(weed_pd['State'] == 'New York') & (weed_pd['month'] == 1) & (weed_pd['year'] == 2015)]['MedQ'].values
weed_pd_mq_ny_jan2015



array([263.56, 263.62, 263.62, 263.58, 263.52, 263.53, 263.55, 263.53,
       263.52, 263.5 , 263.62, 263.64, 263.54, 263.57, 263.51, 263.39,
       263.35, 263.34, 263.34, 263.19, 263.25, 263.16, 263.07, 263.02,
       263.03, 263.08, 262.97, 263.02, 262.99, 262.95, 262.93])

In [64]:
weed_pd_mq_ny_feb2015 = weed_pd[(weed_pd['State'] == 'New York') & (weed_pd['month'] == 2) & (weed_pd['year'] == 2015)]['MedQ'].values
weed_pd_mq_ny_feb2015



array([262.93, 262.93, 262.95, 262.94, 262.92, 262.95, 262.88, 262.9 ,
       262.9 , 262.87, 262.88, 262.91, 262.89, 262.91, 262.9 , 262.86])

In [68]:
print("Mean of NY MedQ for Jan 2015", weed_pd_mq_ny_jan2015.mean())

Mean of NY MedQ for Jan 2015 263.33838709677417


In [71]:
print("Mean of NY MedQ for Feb 2015", weed_pd_mq_ny_feb2015.mean())

Mean of NY MedQ for Feb 2015 262.90749999999997


In [72]:
stats.ttest_ind(weed_pd_mq_ny_jan2015, weed_pd_mq_ny_feb2015)

Ttest_indResult(statistic=6.889244564601663, pvalue=1.4876340462804882e-08)

In [74]:
print('Significant!. Reject Null Hypothesis')

Significant!. Reject Null Hypothesis


### Assumption of t-test

One assumption is that the data used came from a normal distribution. 
<br>
There's a [Shapiro-Wilk test](https://en.wikipedia.org/wiki/Shapiro-Wilk) to test for normality. If p-value is less than 0.05, then there's a low chance that the distribution is normal.

* *Are the `weed_ca_jan2015` and `weed_ca_jan2014` data normally distributed?*

In [28]:
stats.shapiro?

In [13]:
stats.shapiro(weed_ca_jan2015)

(0.9469053149223328, 0.12818680703639984)

In [14]:
stats.shapiro(weed_ca_jan2014)

(0.9353488683700562, 0.06141229346394539)

### A/B testing

Comparing two versions to check which one performs better. Eg: Show to people two variants for the same webpage that they want to see and find which one provides better conversion rate (or the relevant metric). [wiki](https://en.wikipedia.org/wiki/A/B_testing)

**Exercise: Impact of regulation and deregulation.**

* _**CoderGirl**: Use what you've learned above to answer the below two questions._

Information on regulation of Weed in the US by State [wiki](Impact of regulation and deregulation on a couple of states )

1. Alaska legalized it on 4th Nov 2014. Find if prices significantly changed in Dec 2014 compared to Oct 2014. 
2. Maryland decriminalized possessing weed from Oct 1, 2014. Find if prices of weed changed significantly in Oct 2014 compared to Sep 2014

In [78]:
# Your code here

weed_pd_hq_alsk_oct2014 = weed_pd[(weed_pd['State'] == 'Alaska') & (weed_pd['year'] == 2014) & (weed_pd['month'] == 10)]['HighQ'].values
weed_pd_hq_alsk_oct2014


array([291.41, 291.41, 291.76, 291.47, 291.47, 291.47, 291.47, 291.47,
       291.47, 291.47, 291.47, 291.47, 291.47, 291.47, 291.47, 291.47,
       291.95, 291.95, 291.95, 291.95, 291.95, 291.95, 291.95, 291.95,
       291.95, 292.1 , 291.25, 291.25, 291.25, 290.52, 290.52])

In [79]:
weed_pd_hq_alsk_dec2014 = weed_pd[(weed_pd['State'] == 'Alaska') & (weed_pd['year'] == 2014) & (weed_pd['month'] == 12)]['HighQ'].values
weed_pd_hq_alsk_dec2014



array([290.27, 290.67, 290.67, 303.22, 303.22, 303.22, 303.22, 303.22,
       303.22, 303.22, 303.22, 302.91, 302.9 , 302.9 , 302.9 , 302.9 ,
       302.9 , 302.9 , 303.02, 303.02, 303.02, 303.02, 303.02, 303.02,
       303.02, 303.02, 303.02, 303.02, 303.02, 303.02, 303.02])

In [81]:
weed_pd_hq_alsk_oct2014.mean()

291.5525806451613

In [82]:
weed_pd_hq_alsk_dec2014.mean()

301.8367741935485

In [83]:
stats.ttest_ind(weed_pd_hq_alsk_oct2014, weed_pd_hq_alsk_dec2014)

Ttest_indResult(statistic=-15.14330239573019, pvalue=3.655192936628986e-22)

In [86]:
print('p-value <= Level of Significance (0.05). ', 'Results are Significant. ', 'Regularization had a significant impact ')

p-value <= Level of Significance (0.05).  Results are Significant.  Regularization had a significant impact 


<h2> Something to think about: Which of these give smaller p-values ? </h2>
   
   * Smaller effect size
   * Smaller standard error
   * Smaller sample size
   * Higher variance
   
   **Answer:** 

### Chi-square tests

Chi-Square tests are used when the data are frequencies, rather than numerical score/price.

The following two tests make use of chi-square statistic

1. chi-square test for goodness of fit
2. chi-square test for independence

Chi-square test is a non-parametric test. They do not require assumptions about population parameters and they do not test hypotheses about population parameters.

<h2> Chi-Square test for goodness fit </h2>

$$ \chi^2 = \sum (O - E)^2/E $$

* O is observed frequency
* E is expected frequency
* $ \chi $ is the chi-square statistic

Let's assume the proportion of people who bought High, Medium and Low quality weed in Jan-2014 as the expected proportion. Find if proportion of people who bought weed in Jan 2015 conformed to the norm

* Find the total numbers of people who bought High/Med/Low quality weed in January of each year.

In [29]:
weed_jan2014 = weed_pd[(weed_pd.year==2014) & (weed_pd.month==1)][["HighQN", "MedQN", "LowQN"]]
weed_jan2015 = weed_pd[(weed_pd.year==2015) & (weed_pd.month==1)][["HighQN", "MedQN", "LowQN"]]

In [30]:
Expected = np.array(weed_jan2014.apply(sum, axis=0))
Observed = np.array(weed_jan2015.apply(sum, axis=0))

In [18]:
print("Expected:", Expected, "\n" , "Observed:", Observed)

Expected: [2918004 2644757  263958] 
Observed: [4057716 4035049  358088]


* Print the proportions of High/Med/Low quality weed bought and observed.

In [32]:
print("Expected:", Expected/np.sum(Expected.astype(float)), "\n" , "Observed:", Observed/np.sum(Observed.astype(float)))

Expected: [0.5007971  0.45390159 0.04530131] 
 Observed: [0.48015461 0.47747239 0.042373  ]


* Do the Chi-Squared test. What is your result? Were the proportions of people buying high quality weed in Jan 2015 different than expected?

In [33]:
stats.chisquare?

In [20]:
stats.chisquare(______ , ______)

Power_divergenceResult(statistic=1209562.2775169075, pvalue=0.0)

*Inference* : We reject null hypothesis. The proportions in Jan 2015 is different than what was expected.