In [1]:
import numpy as np

In [7]:
# Import `numpy` as `np`
import numpy as np

# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_array)
print(my_array.data)
print(my_array.dtype)
print(my_array.shape)
print(my_array.strides)

[[1 2 3 4]
 [5 6 7 8]]
int64
(2, 4)
(32, 8)


In [8]:
# Create an array of ones
np.ones((3,4))

# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

# Create an array with random values
np.random.random((2,2))

# Create an empty array
np.empty((3,2))

# Create a full array
np.full((2,2),7)

# Create an array of evenly-spaced values
np.arange(10,25,5)

# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
arr = np.ones((3,4),dtype=np.int16)
arr
# arr.strides




array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [33]:
arr1 = np.zeros((2,3,4),dtype=np.int16)
arr1


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [34]:
arr1.strides

(24, 8, 2)

In [60]:
# Create an array with random values
np.random.rand(2)

# ?np.random.rand

array([0.20760446, 0.5246097 ])

In [61]:
np.random.random(2)

array([0.70414443, 0.29195717])

In [64]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [65]:
# Create a full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [67]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [76]:
np.arange(2)

array([0, 1])

In [73]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [81]:
arr = np.loadtxt('data.txt', 
          dtype=int,
          skiprows=1)

arr
arr.strides
arr.dtype

dtype('int64')

In [84]:
arr1 = np.loadtxt('data2.txt', 
          dtype=int,
          skiprows=1,
          delimiter=',')

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr2 = np.genfromtxt('data3.txt',
                    dtype=int,
                    skip_header=1,
                    missing_values='MISSING',
                    filling_values=-99,
                    autostrip=True)

arr2

array([[  1, -99,   3],
       [  4,   5,   6]])

In [96]:
# Save array to Text file

x = np.arange(10,15,1, dtype=int)
print(x)
np.savetxt('test.out', x, delimiter=',')

[10 11 12 13 14]


In [100]:
my_array = np.full((3,4), 9)
print(my_array)

# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

print(my_array.strides)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

# ?my_array  --> For Array attributes help

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
2
12
(32, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
96


In [105]:
# Print the length of `my_array`
print(len(my_array))

# Change the data type of `my_array`
my_flt_array = my_array.astype(float)
print(my_flt_array)

print(my_flt_array.dtype)

print(my_flt_array.strides)

3
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
float64
(32, 8)


In [111]:
m_array = np.array((3,2))

m_array.dtype

f_arr = m_array.astype(float)

f_arr.dtype


dtype('float64')

**ARRAY BROADCASTING**




In [113]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.ones((3,4))

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

(3, 4)
(3, 4)


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [114]:
# Initialize `x`
x = np.ones((3,4))
print(x)

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)
print(y)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[0 1 2 3]
(4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [4]:

# Initialize `x` and `y`
x = np.ones((3,4))
print(x)

y = np.random.random((5,1,4))
print(y)

# Add `x` and `y`
z = x + y
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.19683237 0.93522304 0.70370454 0.86801734]]

 [[0.62061584 0.66765513 0.56151535 0.78988322]]

 [[0.65459596 0.16448586 0.21199111 0.47268204]]

 [[0.61043916 0.10527341 0.81428188 0.01711269]]

 [[0.93189848 0.28287198 0.82655165 0.50618023]]]
[[[1.19683237 1.93522304 1.70370454 1.86801734]
  [1.19683237 1.93522304 1.70370454 1.86801734]
  [1.19683237 1.93522304 1.70370454 1.86801734]]

 [[1.62061584 1.66765513 1.56151535 1.78988322]
  [1.62061584 1.66765513 1.56151535 1.78988322]
  [1.62061584 1.66765513 1.56151535 1.78988322]]

 [[1.65459596 1.16448586 1.21199111 1.47268204]
  [1.65459596 1.16448586 1.21199111 1.47268204]
  [1.65459596 1.16448586 1.21199111 1.47268204]]

 [[1.61043916 1.10527341 1.81428188 1.01711269]
  [1.61043916 1.10527341 1.81428188 1.01711269]
  [1.61043916 1.10527341 1.81428188 1.01711269]]

 [[1.93189848 1.28287198 1.82655165 1.50618023]
  [1.93189848 1.28287198 1.82655165 1.50618023]
  [1.93189848 1.28287198

In [118]:
a = np.array([[1,2,3], [4,8,5], [0, 9, 2]])
print(a)

[[1 2 3]
 [4 8 5]
 [0 9 2]]


In [123]:
print(a.sum())

print(a.max())

print(a.min())

print(a.max(axis=0))

34
9
0
[4 9 5]


In [211]:
np_array_2d = np.arange(0, 6).reshape(2,3)

print(np_array_2d)

[[0 1 2]
 [3 4 5]]


In [130]:
ax_0_sum = np_array_2d.sum(axis=0)
print(ax_0_sum)

print(ax_0_sum.shape)

print(ax_0_sum.ndim)

[3 5 7]
(3,)
1


In [132]:
ax_1_sum = np_array_2d.sum(axis=1)
print(ax_1_sum)

print(ax_1_sum.shape)

print(ax_1_sum.ndim)

[ 3 12]
(2,)
1


In [212]:


x = np.array([[[0], [1], [2]]])
print(x)
print(x.shape)
# (1, 3, 1)


[[[0]
  [1]
  [2]]]
(1, 3, 1)


In [138]:
y = np.squeeze(x)
print(y)
print(y.shape)

# (3,)


[0 1 2]
(3,)


In [213]:
z = np.squeeze(x, axis=0).shape
print(z)
# (3, 1)
# np.squeeze(x, axis=1).shape

# np.squeeze(x, axis=2).shape

(3, 1)


In [215]:

my_array = np.array([1,2,3,4])

my_2d_array = np.array([[1,2,3,4],[5,6,7,8]])

my_3d_array = np.array([ [[1,2,4],[3,4,6]],[[5,6,3],[7,8,0]] ])

# Select items at index 0 and 1
print(my_array[0:2])

print('#########') 
# Select items at row 0 and 1, column 1
print(my_2d_array[0:2,1])  # same as my_2d_array[:,1]

print('#########') 
# Select items at row 1
# This is the same as saying `my_3d_array[1,:,:]` or `my_3d_array[1]`
# print(my_3d_array[1,...])

my_3d_array[[0,1]]



[1 2]
#########
[2 6]
#########


array([[[1, 2, 4],
        [3, 4, 6]],

       [[5, 6, 3],
        [7, 8, 0]]])

In [232]:
# Try out a simple example
print(my_array[my_array<2])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
print(my_3d_array[bigger_than_3])

[1]
[4 3 4 6 5 6 3 7 8]


In [152]:
# Look up info on `mean` with `np.lookfor()` 
print(np.lookfor("mean"))

In [160]:
# Get info on data types with `np.info()`
np.info(np.ndarray.dtype)

In [239]:
print('#############')
print(my_2d_array)

print('#############')
# Select elements at (1,0), (0,1), (1,2) and (0,0)
print(my_2d_array[[1, 0, 1, 0],[0, 1, 2, 0]])

print('#############')
# Select a subset of the rows and columns
print(my_2d_array[[1, 0, 1, 0]])
print(my_2d_array[[1, 0, 1, 0]][:,[0,1,2,0]])

# my_2d_array[[1,0,1]]

#############
[[1 2 3 4]
 [5 6 7 8]]
#############
[5 2 7 1]
#############
[[5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
[[5 6 7 5]
 [1 2 3 1]
 [5 6 7 5]
 [1 2 3 1]]


In [200]:
np.random.random((2,3))

array([[0.41398398, 0.61744374, 0.1322669 ],
       [0.97448122, 0.1806351 , 0.76034991]])

In [204]:
a = np.ones((1,2))

In [207]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [209]:
arr2d = np.zeros((10,10))
arr2d.shape[1]

10

In [226]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [224]:
x[0,...]

array([[1],
       [2],
       [3]])

In [229]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [235]:
np.info(np.mean)

 mean(*args, **kwargs)

Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
out : ndarray, optional
    Alternate output array in which to pl

In [4]:
np.lookfor(med)

NameError: name 'med' is not defined

In [12]:
np.empty((10,1), dtype=int)

array([[-1152921504606846976],
       [-1152921504606846976],
       [                   7],
       [                   0],
       [                   0],
       [                   0],
       [                   0],
       [                   0],
       [                   0],
       [                   0]])

In [2]:
A = np.array([ [1,1,0], [0,1,1], [1,2,3]])
y = np.array([1,4,6])

In [4]:
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 2, 3]])

In [3]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.5, -1.5,  0.5],
       [ 0.5,  1.5, -0.5],
       [-0.5, -0.5,  0.5]])

In [26]:
np.random.seed(1)

In [27]:
np.random.randn(3,2)

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ]])

In [34]:
rs = np.random.RandomState(123)
rs.randn(3,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [32]:
np.random.RandomState?

In [35]:
A = np.array([[1,2], [3,4]])
B = np.array([[3,4], [5,6]])

In [36]:
A * B

array([[ 3,  8],
       [15, 24]])

In [38]:
# Matrix multiplication
np.matmul(A, B)

array([[13, 16],
       [29, 36]])

In [6]:
A = np.array([[3,4], [2,16]])

In [41]:
# Matrix Inverse
np.linalg.inv(A)

array([[ 0.4  , -0.1  ],
       [-0.05 ,  0.075]])

In [44]:
# Transpose
np.transpose(A)

array([[ 3,  2],
       [ 4, 16]])

In [48]:
A[0,1]


4

In [7]:
A

array([[ 3,  4],
       [ 2, 16]])

In [8]:
A < 4


array([[ True, False],
       [ True, False]])

In [15]:
B = A[A < 4]
B

array([3, 2])

In [19]:
B.shape

(2,)

In [2]:
zz = np.random.random((2,2))

In [3]:
zz

array([[0.12308836, 0.12399085],
       [0.81549232, 0.88586106]])

In [4]:
zz[zz > 0.5]

array([0.81549232, 0.88586106])

In [5]:
zz[:]

array([[0.12308836, 0.12399085],
       [0.81549232, 0.88586106]])